// 简化版 CET-4 示例词库（约 40 个）
// 数据结构遵循 PRD：id, word, phonetic, definition, example
// 可选 mnemonic 字段用于趣味联想

const WORDS = [
  { id: 1,  word: "abstract", phonetic: "/ˈæbstrækt/", definition: "adj. 抽象的；理论的", example: "This is an abstract concept.", mnemonic: "想不明白的东西就是抽象" },
  { id: 2,  word: "access", phonetic: "/ˈækses/", definition: "n./v. 进入；访问", example: "You need a password to access the system." },
  { id: 3,  word: "adapt", phonetic: "/əˈdæpt/", definition: "v. 适应；改编", example: "They quickly adapted to the new environment." },
  { id: 4,  word: "allocate", phonetic: "/ˈæləkeɪt/", definition: "v. 分配；拨给", example: "The budget was allocated to several projects." },
  { id: 5,  word: "analyze", phonetic: "/ˈænəlaɪz/", definition: "v. 分析", example: "We need to analyze the data carefully." },
  { id: 6,  word: "approach", phonetic: "/əˈprəʊtʃ/", definition: "n./v. 方法；接近", example: "This approach may solve the problem." },
  { id: 7,  word: "assist", phonetic: "/əˈsɪst/", definition: "v. 协助，帮助", example: "She assisted him with the homework." },
  { id: 8,  word: "assume", phonetic: "/əˈsjuːm/", definition: "v. 假定；设想", example: "Let's assume the report is correct." },
  { id: 9,  word: "attempt", phonetic: "/əˈtempt/", definition: "n./v. 尝试", example: "This is his first attempt." },
  { id: 10, word: "available", phonetic: "/əˈveɪləbl/", definition: "adj. 可用的；可获得的", example: "The book is not available now." },
  { id: 11, word: "aware", phonetic: "/əˈweə/", definition: "adj. 意识到的", example: "I am aware of the risks." },
  { id: 12, word: "benefit", phonetic: "/ˈbenɪfɪt/", definition: "n./v. 好处；受益", example: "Exercise has many benefits." },
  { id: 13, word: "challenge", phonetic: "/ˈtʃælɪndʒ/", definition: "n./v. 挑战", example: "This task is a challenge for us." },
  { id: 14, word: "communicate", phonetic: "/kəˈmjuːnɪkeɪt/", definition: "v. 沟通；交流", example: "We communicate by email." },
  { id: 15, word: "compare", phonetic: "/kəmˈpeə/", definition: "v. 比较", example: "Compare the two results." },
  { id: 16, word: "compile", phonetic: "/kəmˈpaɪl/", definition: "v. 编译；汇编", example: "The program failed to compile." },
  { id: 17, word: "conclude", phonetic: "/kənˈkluːd/", definition: "v. 总结；得出结论", example: "We conclude that the method works." },
  { id: 18, word: "consider", phonetic: "/kənˈsɪdə/", definition: "v. 考虑", example: "Consider all options carefully." },
  { id: 19, word: "consume", phonetic: "/kənˈsjuːm/", definition: "v. 消耗；消费", example: "This app consumes little memory." },
  { id: 20, word: "contrast", phonetic: "/ˈkɒntrɑːst/", definition: "n./v. 对比；差异", example: "The contrast is obvious." },
  { id: 21, word: "create", phonetic: "/kriːˈeɪt/", definition: "v. 创造；创建", example: "Create a new file." },
  { id: 22, word: "declare", phonetic: "/dɪˈkleə/", definition: "v. 声明；宣告", example: "He declared victory." },
  { id: 23, word: "define", phonetic: "/dɪˈfaɪn/", definition: "v. 定义", example: "Define your goals." },
  { id: 24, word: "deliver", phonetic: "/dɪˈlɪvə/", definition: "v. 递送；实现", example: "They delivered the project on time." },
  { id: 25, word: "design", phonetic: "/dɪˈzaɪn/", definition: "v./n. 设计", example: "Design a new logo." },
  { id: 26, word: "develop", phonetic: "/dɪˈveləp/", definition: "v. 开发；发展", example: "Develop a web app." },
  { id: 27, word: "discuss", phonetic: "/dɪˈskʌs/", definition: "v. 讨论", example: "We discussed the plan." },
  { id: 28, word: "efficient", phonetic: "/ɪˈfɪʃnt/", definition: "adj. 高效的", example: "An efficient solution is needed." },
  { id: 29, word: "element", phonetic: "/ˈelɪmənt/", definition: "n. 元素；成分", example: "Key elements of success." },
  { id: 30, word: "evidence", phonetic: "/ˈevɪdəns/", definition: "n. 证据", example: "There is no evidence." },
  { id: 31, word: "exclude", phonetic: "/ɪksˈkluːd/", definition: "v. 排除；不包括", example: "Taxes are excluded." },
  { id: 32, word: "expand", phonetic: "/ɪkˈspænd/", definition: "v. 扩展；膨胀", example: "Expand the team." },
  { id: 33, word: "feature", phonetic: "/ˈfiːtʃə/", definition: "n./v. 特征；以…为特色", example: "New features are released." },
  { id: 34, word: "focus", phonetic: "/ˈfəʊkəs/", definition: "n./v. 焦点；专注", example: "Focus on the problem." },
  { id: 35, word: "generate", phonetic: "/ˈdʒenəreɪt/", definition: "v. 生成；产生", example: "Generate a report." },
  { id: 36, word: "impact", phonetic: "/ˈɪmpækt/", definition: "n./v. 影响；冲击", example: "The policy impacted the market." },
  { id: 37, word: "maintain", phonetic: "/meɪnˈteɪn/", definition: "v. 维护；保持", example: "Maintain good habits." },
  { id: 38, word: "method", phonetic: "/ˈmeθəd/", definition: "n. 方法", example: "A scientific method." },
  { id: 39, word: "option", phonetic: "/ˈɒpʃn/", definition: "n. 选项", example: "There are several options." },
  { id: 40, word: "process", phonetic: "/ˈprəʊses/", definition: "n./v. 过程；处理", example: "Process the data." }
];
